[package]
name = "mon-projet"
version = "0.1.0"
edition = "2021"

[dependencies]
windows = { version = "0.58", features = [
    "Win32_Foundation",
    "Win32_System_Memory"
] }

[[bin]]
name = "mon-projet"
path = "src/win32-exec.rs"